.PHONY: clean All

All:
	@echo "----------Building project:[ a - Debug ]----------"
	@cd "a" && "$(MAKE)" -f  "a.mk"
clean:
	@echo "----------Cleaning project:[ a - Debug ]----------"
	@cd "a" && "$(MAKE)" -f  "a.mk" clean
