.PHONY: clean All

All:
	@echo "----------Building project:[ HolaMundoEjemplo - Debug ]----------"
	@cd "HolaMundoEjemplo" && "$(MAKE)" -f  "HolaMundoEjemplo.mk"
clean:
	@echo "----------Cleaning project:[ HolaMundoEjemplo - Debug ]----------"
	@cd "HolaMundoEjemplo" && "$(MAKE)" -f  "HolaMundoEjemplo.mk" clean
