.PHONY: clean All

All:
	@echo "----------Building project:[ HolaMundillo - Debug ]----------"
	@cd "HolaMundillo" && "$(MAKE)" -f  "HolaMundillo.mk"
clean:
	@echo "----------Cleaning project:[ HolaMundillo - Debug ]----------"
	@cd "HolaMundillo" && "$(MAKE)" -f  "HolaMundillo.mk" clean
